version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build:
      context: ./api
    container_name: api_service
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq

  worker:
    build:
      context: ./worker
    container_name: worker_service
    depends_on:
      - rabbitmq
